#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"

#line 12 "parser.y"
typedef union{
	int integer;
	float floating_point;
	char *sym;

} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif
#line 21 "parser.y"
	
	#include <stdio.h>
	#include <stdlib.h>
	#include <string.h>
	#include <limits.h>

	int size=20;
	char *alc=0;
	int globalIndex=0;
	int globalScope=1;
	#define ANSI_COLOR_RED     "\x1b[31m"
	#define ANSI_COLOR_RESET   "\x1b[0m"
	
	struct Stack
	{
    	int top;
    	unsigned capacity;
    	int* array;
	};

	struct Stack* createStack(unsigned capacity)
	{
	    struct Stack* stack = (struct Stack*) malloc(sizeof(struct Stack));
	    stack->capacity = capacity;
	    stack->top = -1;
	    stack->array = (int*) malloc(stack->capacity * sizeof(int));
	    return stack;
	}

	int isFull(struct Stack* stack)
	{   return stack->top == stack->capacity - 1; }
	 
	int isEmpty(struct Stack* stack)
	{   return stack->top == -1;  }
	 
	void push(struct Stack* stack, int item)
	{
	    if (isFull(stack))
	        return;
	    stack->array[++stack->top] = item;
	}
	 
	int pop(struct Stack* stack)
	{
	    if (isEmpty(stack))
	        return INT_MIN;
	    return stack->array[stack->top--];
	}

	struct symbolTable{
		int index;
		char *symbol;
		char *attribute;
		char *data;
		struct symbolTable *next;
		int scope;
	};
	
	struct symbolTable *hash[2][20];
	struct Stack* stack;
	int i=0;
	
	void init()
	{
	 	stack = createStack(100);
		for(;i<size;i++)
		{
			hash[0][i] = NULL;
			hash[1][i] = NULL;
		}
	}
	
	int hashLocation(char *sym)
	{
		int sum=0;
		size_t length = strlen(sym);
		int k=0;
		for(;k<length;k++)
		{
			sum = sum + (int)sym[k];
		}
		return sum%size;
	}

	int searchHash(int type, char *sym, int x)
	{
		struct symbolTable *temp = hash[type][x];
		while(temp!=NULL)
		{
			if (strcmp(temp->symbol, sym)==0)
			{
				return 0;
			}
			temp=temp->next;
		}
		return 1;
	}

	void addToTable(int type, char *sym, char *attr, char *dat)
	{
		int x = hashLocation(sym);
		if (searchHash(type, sym, x)==0)
			return;	
		struct symbolTable *newSymbol = (struct symbolTable *)malloc(sizeof(struct symbolTable));
		char *te = (char *)malloc(strlen(sym)+1);
		strcpy(te, sym);
		printf("\nArgument passed: %s\n", sym);
		newSymbol->symbol = te;
		newSymbol->attribute = attr;
		newSymbol->data = dat;
		newSymbol->next = NULL;
		newSymbol->index = globalIndex + 1;
		newSymbol->scope = globalScope - 1;
		globalIndex++;
		struct symbolTable *temp = hash[type][x];
		hash[type][x] = newSymbol;
		hash[type][x]->next = temp;
	}

	int searchHashScope(char *sym, int x)
	{
		struct symbolTable *temp = hash[0][x];
		while(temp!=NULL)
		{
			if (strcmp(temp->symbol, sym)==0 && globalScope -1 == temp->scope)
			{ return 0; }
			temp=temp->next;
		}
		return 1;
	}

	// This returns 0 if an identifier is already declared in the same scope
	int checkDeclaration(char *sym) 
	{
		int x = hashLocation(sym);
		if(searchHashScope(sym, x))
		return 1;
		else
		return 0;
	}

	void display()
	{
		int k=0;
		printf("\n\nSYMBOL TABLE:\n");
		printf("------------------------------------------------------------------------------------------------------------\n");
		printf("%*s\t|\t%*s\t|\t%*s\t|\t%*s\t|\t%*s\n", 10, "INDEX", 10, "SYMBOL", 10, "ATTRIBUTE", 10, "DATATYPE", 10, "SCOPE");
		printf("------------------------------------------------------------------------------------------------------------\n");
		for(;k<size;k++)
		{
			struct symbolTable *temp = hash[0][k];
			while(temp!=NULL)
			{
				printf("%*d\t|\t%*s\t|\t%*s\t|\t%*s\t|\t%*d\n",10, temp->index, 10, temp->symbol, 10, temp->attribute, 10, temp->data, 10, temp->scope);
				temp = temp->next;
			}
		}
		printf("-------------------------------------------------------------------------------------------------------------\n");
		k=0;
		printf("\n\nCONSTANT TABLE:\n");
		printf("-------------------------------------------------------------------\n");
		printf("%*s\t|\t%*s\t|\t%*s\n", 10, "INDEX", 10, "SYMBOL", 10, "ATTRIBUTE");
		printf("-------------------------------------------------------------------\n");
		for(;k<size;k++)
		{
			struct symbolTable *temp = hash[1][k];
			while(temp!=NULL)
			{
				printf("%*d\t|\t%*s\t|\t%*s\n",10, temp->index, 10, temp->symbol, 10, temp->attribute);
				temp = temp->next;
			}
		}
		printf("-------------------------------------------------------------------\n");
	}

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	ID	258
#define	CONSTANT	259
#define	STR	260
#define	HEADERFILE	261
#define	INC	262
#define	DEC	263
#define	LE	264
#define	GE	265
#define	EQ	266
#define	NE	267
#define	AND	268
#define	OR	269
#define	LEFT	270
#define	RIGHT	271
#define	MUL_ASSIGN	272
#define	DIV_ASSIGN	273
#define	MOD_ASSIGN	274
#define	ADD_ASSIGN	275
#define	SUB_ASSIGN	276
#define	LEFT_ASSIGN	277
#define	RIGHT_ASSIGN	278
#define	AND_ASSIGN	279
#define	XOR_ASSIGN	280
#define	OR_ASSIGN	281
#define	AUTO	282
#define	BREAK	283
#define	CASE	284
#define	CHAR	285
#define	CONST	286
#define	CONTINUE	287
#define	DEFAULT	288
#define	DO	289
#define	DOUBLE	290
#define	ELSE	291
#define	ENUM	292
#define	EXTERN	293
#define	FLOAT	294
#define	FOR	295
#define	GOTO	296
#define	IF	297
#define	INT	298
#define	LONG	299
#define	REGISTER	300
#define	RETURN	301
#define	SHORT	302
#define	SIGNED	303
#define	SIZEOF	304
#define	STATIC	305
#define	STRUCT	306
#define	SWITCH	307
#define	TYPEDEF	308
#define	UNION	309
#define	UNSIGNED	310
#define	VOID	311
#define	VOLATILE	312
#define	WHILE	313


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int ID;
static const int CONSTANT;
static const int STR;
static const int HEADERFILE;
static const int INC;
static const int DEC;
static const int LE;
static const int GE;
static const int EQ;
static const int NE;
static const int AND;
static const int OR;
static const int LEFT;
static const int RIGHT;
static const int MUL_ASSIGN;
static const int DIV_ASSIGN;
static const int MOD_ASSIGN;
static const int ADD_ASSIGN;
static const int SUB_ASSIGN;
static const int LEFT_ASSIGN;
static const int RIGHT_ASSIGN;
static const int AND_ASSIGN;
static const int XOR_ASSIGN;
static const int OR_ASSIGN;
static const int AUTO;
static const int BREAK;
static const int CASE;
static const int CHAR;
static const int CONST;
static const int CONTINUE;
static const int DEFAULT;
static const int DO;
static const int DOUBLE;
static const int ELSE;
static const int ENUM;
static const int EXTERN;
static const int FLOAT;
static const int FOR;
static const int GOTO;
static const int IF;
static const int INT;
static const int LONG;
static const int REGISTER;
static const int RETURN;
static const int SHORT;
static const int SIGNED;
static const int SIZEOF;
static const int STATIC;
static const int STRUCT;
static const int SWITCH;
static const int TYPEDEF;
static const int UNION;
static const int UNSIGNED;
static const int VOID;
static const int VOLATILE;
static const int WHILE;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,ID=258
	,CONSTANT=259
	,STR=260
	,HEADERFILE=261
	,INC=262
	,DEC=263
	,LE=264
	,GE=265
	,EQ=266
	,NE=267
	,AND=268
	,OR=269
	,LEFT=270
	,RIGHT=271
	,MUL_ASSIGN=272
	,DIV_ASSIGN=273
	,MOD_ASSIGN=274
	,ADD_ASSIGN=275
	,SUB_ASSIGN=276
	,LEFT_ASSIGN=277
	,RIGHT_ASSIGN=278
	,AND_ASSIGN=279
	,XOR_ASSIGN=280
	,OR_ASSIGN=281
	,AUTO=282
	,BREAK=283
	,CASE=284
	,CHAR=285
	,CONST=286
	,CONTINUE=287
	,DEFAULT=288
	,DO=289
	,DOUBLE=290
	,ELSE=291
	,ENUM=292
	,EXTERN=293
	,FLOAT=294
	,FOR=295
	,GOTO=296
	,IF=297
	,INT=298
	,LONG=299
	,REGISTER=300
	,RETURN=301
	,SHORT=302
	,SIGNED=303
	,SIZEOF=304
	,STATIC=305
	,STRUCT=306
	,SWITCH=307
	,TYPEDEF=308
	,UNION=309
	,UNSIGNED=310
	,VOID=311
	,VOLATILE=312
	,WHILE=313


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::ID=258;
const int YY_parse_CLASS::CONSTANT=259;
const int YY_parse_CLASS::STR=260;
const int YY_parse_CLASS::HEADERFILE=261;
const int YY_parse_CLASS::INC=262;
const int YY_parse_CLASS::DEC=263;
const int YY_parse_CLASS::LE=264;
const int YY_parse_CLASS::GE=265;
const int YY_parse_CLASS::EQ=266;
const int YY_parse_CLASS::NE=267;
const int YY_parse_CLASS::AND=268;
const int YY_parse_CLASS::OR=269;
const int YY_parse_CLASS::LEFT=270;
const int YY_parse_CLASS::RIGHT=271;
const int YY_parse_CLASS::MUL_ASSIGN=272;
const int YY_parse_CLASS::DIV_ASSIGN=273;
const int YY_parse_CLASS::MOD_ASSIGN=274;
const int YY_parse_CLASS::ADD_ASSIGN=275;
const int YY_parse_CLASS::SUB_ASSIGN=276;
const int YY_parse_CLASS::LEFT_ASSIGN=277;
const int YY_parse_CLASS::RIGHT_ASSIGN=278;
const int YY_parse_CLASS::AND_ASSIGN=279;
const int YY_parse_CLASS::XOR_ASSIGN=280;
const int YY_parse_CLASS::OR_ASSIGN=281;
const int YY_parse_CLASS::AUTO=282;
const int YY_parse_CLASS::BREAK=283;
const int YY_parse_CLASS::CASE=284;
const int YY_parse_CLASS::CHAR=285;
const int YY_parse_CLASS::CONST=286;
const int YY_parse_CLASS::CONTINUE=287;
const int YY_parse_CLASS::DEFAULT=288;
const int YY_parse_CLASS::DO=289;
const int YY_parse_CLASS::DOUBLE=290;
const int YY_parse_CLASS::ELSE=291;
const int YY_parse_CLASS::ENUM=292;
const int YY_parse_CLASS::EXTERN=293;
const int YY_parse_CLASS::FLOAT=294;
const int YY_parse_CLASS::FOR=295;
const int YY_parse_CLASS::GOTO=296;
const int YY_parse_CLASS::IF=297;
const int YY_parse_CLASS::INT=298;
const int YY_parse_CLASS::LONG=299;
const int YY_parse_CLASS::REGISTER=300;
const int YY_parse_CLASS::RETURN=301;
const int YY_parse_CLASS::SHORT=302;
const int YY_parse_CLASS::SIGNED=303;
const int YY_parse_CLASS::SIZEOF=304;
const int YY_parse_CLASS::STATIC=305;
const int YY_parse_CLASS::STRUCT=306;
const int YY_parse_CLASS::SWITCH=307;
const int YY_parse_CLASS::TYPEDEF=308;
const int YY_parse_CLASS::UNION=309;
const int YY_parse_CLASS::UNSIGNED=310;
const int YY_parse_CLASS::VOID=311;
const int YY_parse_CLASS::VOLATILE=312;
const int YY_parse_CLASS::WHILE=313;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		240
#define	YYFLAG		-32768
#define	YYNTBASE	83

#define YYTRANSLATE(x) ((unsigned)(x) <= 313 ? yytranslate[x] : 134)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    72,     2,     2,     2,    74,    67,     2,    62,
    63,    68,    69,    61,    70,    66,    73,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    80,    59,    75,
    60,    76,    79,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    64,     2,    65,    77,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    81,    78,    82,    71,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     4,     6,     8,    10,    12,    14,    16,    18,
    20,    22,    24,    26,    28,    30,    32,    34,    36,    38,
    41,    43,    46,    48,    51,    54,    58,    62,    64,    66,
    70,    72,    77,    80,    84,    90,    96,   102,   104,   108,
   112,   116,   124,   132,   134,   142,   148,   154,   157,   159,
   163,   165,   167,   169,   173,   175,   180,   184,   189,   193,
   196,   199,   201,   205,   207,   210,   213,   216,   219,   224,
   226,   228,   230,   232,   234,   236,   238,   243,   245,   249,
   253,   257,   259,   263,   267,   269,   273,   277,   279,   283,
   287,   291,   295,   297,   301,   305,   307,   311,   313,   317,
   319,   323,   325,   329,   331,   335,   337,   343,   345,   349,
   351,   353,   355,   357,   359,   361,   363,   365,   367,   369,
   371,   374,   377,   380,   384,   388,   391,   393,   395,   397,
   400,   402,   404,   406,   413,   419,   427,   434,   439,   445,
   447,   449,   451,   453,   455
};

static const short yyrhs[] = {    47,
     0,    43,     0,    44,     0,    39,     0,    35,     0,    56,
     0,    87,     0,    95,     0,    97,     0,    98,     0,    99,
     0,   120,     0,   121,     0,    59,     0,    87,     0,    98,
     0,    99,     0,   120,     0,   121,     0,    86,    84,     0,
    84,     0,    93,    59,     0,   127,     0,    83,     3,     0,
    83,     3,     0,    89,    60,   132,     0,    89,    60,   133,
     0,    90,     0,    89,     0,    92,    61,    91,     0,    91,
     0,    83,   131,    61,    94,     0,    83,   131,     0,    94,
    61,   130,     0,    94,    61,   130,    60,   133,     0,    94,
    61,   130,    60,   132,     0,    94,    61,   130,    60,   129,
     0,   130,     0,   130,    60,   133,     0,   130,    60,   132,
     0,   130,    60,   129,     0,    42,    62,   100,    63,    96,
    36,    96,     0,    42,    62,   100,    63,    96,    36,    96,
     0,    85,     0,    42,    62,   100,    63,    96,    36,    97,
     0,    42,    62,   100,    63,    85,     0,    58,    62,   100,
    63,    84,     0,   100,    59,     0,   118,     0,   100,    61,
   118,     0,   129,     0,   132,     0,   133,     0,    62,   100,
    63,     0,   101,     0,   102,    64,   100,    65,     0,   102,
    62,    63,     0,   102,    62,   103,    63,     0,   102,    66,
   129,     0,   102,     7,     0,   102,     8,     0,   118,     0,
   103,    61,   118,     0,   102,     0,     7,   104,     0,     8,
   104,     0,   105,   106,     0,    49,   104,     0,    49,    62,
    83,    63,     0,    67,     0,    68,     0,    69,     0,    70,
     0,    71,     0,    72,     0,   104,     0,    62,    83,    63,
   106,     0,   106,     0,   107,    68,   106,     0,   107,    73,
   106,     0,   107,    74,   106,     0,   107,     0,   108,    69,
   107,     0,   108,    70,   107,     0,   108,     0,   109,    15,
   108,     0,   109,    16,   108,     0,   109,     0,   110,    75,
   109,     0,   110,    76,   109,     0,   110,     9,   109,     0,
   110,    10,   109,     0,   110,     0,   111,    11,   110,     0,
   111,    12,   110,     0,   111,     0,   112,    67,   111,     0,
   112,     0,   113,    77,   112,     0,   113,     0,   114,    78,
   113,     0,   114,     0,   115,    13,   114,     0,   115,     0,
   116,    14,   115,     0,   116,     0,   116,    79,   100,    80,
   117,     0,   117,     0,   104,   119,   118,     0,    60,     0,
    17,     0,    18,     0,    19,     0,    20,     0,    21,     0,
    22,     0,    23,     0,    24,     0,    25,     0,    26,     0,
    32,    59,     0,    28,    59,     0,    46,    59,     0,    46,
   100,    59,     0,   122,    86,   123,     0,   122,   123,     0,
    81,     0,    82,     0,   125,     0,   124,   125,     0,   126,
     0,    87,     0,     6,     0,    88,   128,    63,    81,    86,
   123,     0,    88,   128,    63,    81,   123,     0,    88,   128,
    92,    63,    81,    86,   123,     0,    88,   128,    92,    63,
    81,   123,     0,    88,    62,    63,    59,     0,    88,   128,
    92,    63,    59,     0,    62,     0,     3,     0,     3,     0,
     3,     0,     4,     0,     5,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   200,   201,   202,   203,   204,   205,   210,   211,   212,   213,
   214,   215,   216,   217,   220,   221,   222,   223,   224,   227,
   228,   235,   236,   239,   258,   271,   272,   275,   276,   279,
   280,   283,   284,   287,   288,   289,   290,   291,   292,   293,
   294,   308,   310,   311,   313,   314,   327,   335,   337,   338,
   341,   342,   343,   344,   347,   348,   349,   350,   351,   352,
   353,   357,   358,   362,   363,   364,   365,   366,   367,   370,
   371,   372,   373,   374,   375,   378,   379,   382,   383,   384,
   385,   388,   389,   390,   393,   394,   395,   398,   399,   400,
   401,   402,   405,   406,   407,   410,   411,   414,   415,   418,
   419,   422,   423,   426,   427,   430,   431,   434,   435,   438,
   439,   440,   441,   442,   443,   444,   445,   446,   447,   448,
   453,   454,   455,   456,   465,   466,   469,   471,   483,   484,
   488,   489,   490,   494,   495,   496,   497,   500,   501,   504,
   507,   517,   530,   552,   553
};

static const char * const yytname[] = {   "$","error","$illegal.","ID","CONSTANT",
"STR","HEADERFILE","INC","DEC","LE","GE","EQ","NE","AND","OR","LEFT","RIGHT",
"MUL_ASSIGN","DIV_ASSIGN","MOD_ASSIGN","ADD_ASSIGN","SUB_ASSIGN","LEFT_ASSIGN",
"RIGHT_ASSIGN","AND_ASSIGN","XOR_ASSIGN","OR_ASSIGN","AUTO","BREAK","CASE","CHAR",
"CONST","CONTINUE","DEFAULT","DO","DOUBLE","ELSE","ENUM","EXTERN","FLOAT","FOR",
"GOTO","IF","INT","LONG","REGISTER","RETURN","SHORT","SIGNED","SIZEOF","STATIC",
"STRUCT","SWITCH","TYPEDEF","UNION","UNSIGNED","VOID","VOLATILE","WHILE","';'",
"'='","','","'('","')'","'['","']'","'.'","'&'","'*'","'+'","'-'","'~'","'!'",
"'/'","'%'","'<'","'>'","'^'","'|'","'?'","':'","'{'","'}'","dataType","statement",
"statement1","statements","declarationStatement","declaration","declaration1",
"declarationAndAssignment","completeDeclaration","argumentList","declarationList",
"identifierList","ifAndElseMatched","ifAndElseMatched1","ifAndElseUnmatched",
"whileLoopStatement","expressionStatement","expression","primary_expression",
"postfix_expression","argument_expression_list","unary_expression","unary_operator",
"cast_expression","multiplicative_expression","additive_expression","shift_expression",
"relational_expression","equality_expression","and_expression","exclusive_or_expression",
"inclusive_or_expression","logical_and_expression","logical_or_expression","conditional_expression",
"assignment_expression","assignment_operator","jumpStatement","compoundStatement",
"startCompound","endCompound","startSymbol","external_declaration","functionDefinition",
"functionDeclaration","startParenthesis","identi","identi1","identi2","consta",
"stri",""
};
#endif

static const short yyr1[] = {     0,
    83,    83,    83,    83,    83,    83,    84,    84,    84,    84,
    84,    84,    84,    84,    85,    85,    85,    85,    85,    86,
    86,    87,    87,    88,    89,    90,    90,    91,    91,    92,
    92,    93,    93,    94,    94,    94,    94,    94,    94,    94,
    94,    95,    96,    96,    97,    97,    98,    99,   100,   100,
   101,   101,   101,   101,   102,   102,   102,   102,   102,   102,
   102,   103,   103,   104,   104,   104,   104,   104,   104,   105,
   105,   105,   105,   105,   105,   106,   106,   107,   107,   107,
   107,   108,   108,   108,   109,   109,   109,   110,   110,   110,
   110,   110,   111,   111,   111,   112,   112,   113,   113,   114,
   114,   115,   115,   116,   116,   117,   117,   118,   118,   119,
   119,   119,   119,   119,   119,   119,   119,   119,   119,   119,
   120,   120,   120,   120,   121,   121,   122,   123,   124,   124,
   125,   125,   125,   126,   126,   126,   126,   127,   127,   128,
   129,   130,   131,   132,   133
};

static const short yyr2[] = {     0,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     2,
     1,     2,     1,     2,     2,     3,     3,     1,     1,     3,
     1,     4,     2,     3,     5,     5,     5,     1,     3,     3,
     3,     7,     7,     1,     7,     5,     5,     2,     1,     3,
     1,     1,     1,     3,     1,     4,     3,     4,     3,     2,
     2,     1,     3,     1,     2,     2,     2,     2,     4,     1,
     1,     1,     1,     1,     1,     1,     4,     1,     3,     3,
     3,     1,     3,     3,     1,     3,     3,     1,     3,     3,
     3,     3,     1,     3,     3,     1,     3,     1,     3,     1,
     3,     1,     3,     1,     3,     1,     5,     1,     3,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     2,     2,     2,     3,     3,     2,     1,     1,     1,     2,
     1,     1,     1,     6,     5,     7,     6,     4,     5,     1,
     1,     1,     1,     1,     1
};

static const short yydefact[] = {     0,
   133,     5,     4,     2,     3,     1,     6,     0,   132,     0,
     0,     0,   129,   131,    23,   143,    33,   140,     0,    22,
   130,     0,     0,     0,     0,    29,    28,    31,     0,   142,
    32,    38,   138,     0,    25,     0,     0,     0,     0,     0,
   141,   144,   145,     0,     0,     0,     0,     0,     0,     0,
     0,    14,     0,    70,    71,    72,    73,    74,    75,   127,
   128,    21,     0,     7,     0,     8,     9,    10,    11,     0,
    55,    64,    76,     0,    78,    82,    85,    88,    93,    96,
    98,   100,   102,   104,   106,   108,    49,    12,    13,     0,
   135,    51,    52,    53,    26,    27,    30,   139,     0,    34,
    41,    40,    39,     0,    65,    66,   122,   121,     0,   123,
     0,     0,    68,     0,     0,     0,    20,   134,     0,    48,
     0,    60,    61,     0,     0,     0,   111,   112,   113,   114,
   115,   116,   117,   118,   119,   120,   110,     0,    76,    67,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
   126,     0,   137,     0,     0,   124,     0,     0,     0,    54,
     0,    50,    57,     0,    62,     0,    59,   109,    79,    80,
    81,    83,    84,    86,    87,    91,    92,    89,    90,    94,
    95,    97,    99,   101,   103,   105,     0,   125,   136,    37,
    36,    35,     0,    69,     0,    77,     0,     0,    58,    56,
     0,     0,    46,    15,     0,    16,    17,    18,    19,    47,
    63,   107,     0,     0,     0,     0,    44,    42,    45,     0,
     0,     0,     0,     0,     0,    43,     0,     0,     0,     0
};

static const short yydefgoto[] = {     8,
    62,   227,    63,    64,    65,    26,    27,    28,    29,    11,
    31,    66,   236,    67,    68,    69,    70,    71,    72,   174,
    73,    74,    75,    76,    77,    78,    79,    80,    81,    82,
    83,    84,    85,    86,    87,   138,    88,    89,    90,    91,
    12,    13,    14,    15,    19,    92,    32,    17,    93,    94
};

static const short yypact[] = {   525,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,    29,-32768,   -16,
    -6,    51,-32768,-32768,-32768,    16,    32,    37,   400,-32768,
-32768,    81,    47,    52,   139,    92,-32768,-32768,   -24,-32768,
    99,   103,-32768,   146,-32768,    20,   498,   -41,    81,   134,
-32768,-32768,-32768,   433,   433,   117,   121,   125,   383,   457,
   129,-32768,   359,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,   146,-32768,   -16,-32768,-32768,-32768,-32768,    44,
-32768,    21,   147,   481,-32768,    23,     1,    66,     4,    48,
   131,   132,   128,   198,    -4,-32768,-32768,-32768,-32768,   146,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,   146,   169,
-32768,-32768,-32768,   481,-32768,-32768,-32768,-32768,   481,-32768,
    82,   359,-32768,   481,   173,    94,-32768,-32768,   498,-32768,
   481,-32768,-32768,   409,   481,   229,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,   481,-32768,-32768,
   481,   481,   481,   481,   481,   481,   481,   481,   481,   481,
   481,   481,   481,   481,   481,   481,   481,   481,   481,   146,
-32768,   146,-32768,   134,    95,-32768,   177,    98,   481,-32768,
   116,-32768,-32768,   123,-32768,   -13,-32768,-32768,-32768,-32768,
-32768,    23,    23,     1,     1,    66,    66,    66,    66,     4,
     4,    48,   131,   132,   128,   198,   -31,-32768,-32768,-32768,
-32768,-32768,   265,-32768,   218,-32768,   189,   481,-32768,-32768,
   481,   187,   215,-32768,   216,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,   481,   312,   133,   192,-32768,-32768,-32768,   265,
   481,   219,   136,   265,   265,-32768,   220,   312,   258,-32768
};

static const short yypgoto[] = {   -10,
   -61,  -170,   -64,     0,    19,-32768,-32768,   222,   144,-32768,
-32768,-32768,  -161,  -202,  -180,  -162,   -48,-32768,-32768,-32768,
   -29,-32768,    -7,   -56,    54,    -3,    67,   112,   120,   115,
   122,   124,-32768,    70,  -104,-32768,     7,     9,-32768,   -52,
-32768,   266,-32768,-32768,   226,   -34,   244,-32768,   -33,   -32
};


#define	YYLAST		581


static const short yytable[] = {     9,
   111,   117,    95,    96,   116,   101,   102,   103,    25,   158,
   118,     9,   148,   149,   105,   106,   172,    98,    10,   175,
   113,   229,   216,    42,    43,   160,    25,   122,   123,   121,
    10,    16,   213,   178,   162,   229,    37,   161,    38,    99,
   217,   215,   115,   216,   139,    18,   163,   121,   211,   216,
   239,   210,    20,   216,   216,   116,     1,   216,   152,   153,
   165,   217,   228,   116,   213,   168,   140,   217,   232,   144,
   145,   217,   217,   237,   159,   217,   176,   -24,   150,   151,
   146,   147,   124,    30,   125,     2,   126,   182,   183,     3,
   141,   177,    22,     4,     5,   142,   143,     6,   117,    23,
   117,   167,   120,   221,   121,    33,     7,   198,    25,   199,
   197,   139,   139,   139,   139,   139,   139,   139,   139,   139,
   139,   139,   139,   139,   139,   139,   139,   139,   139,   200,
   201,   202,    34,   179,   180,   181,    41,    42,    43,   139,
   166,    35,   121,   220,   186,   187,   188,   189,    41,    42,
    43,    36,    44,    45,   121,   121,   170,   203,   121,    39,
   205,   206,    40,   127,   128,   129,   130,   131,   132,   133,
   134,   135,   136,    46,   225,   107,    37,    47,   207,   108,
     2,   139,   233,   208,     3,   209,   109,    48,     4,     5,
   114,    49,     6,   121,    50,   230,   121,   154,   235,   184,
   185,     7,   214,    51,    52,   156,   137,    53,   155,   218,
   157,   219,    54,    55,    56,    57,    58,    59,   190,   191,
    41,    42,    43,   214,    44,    45,    60,    61,   164,   214,
   218,    41,   219,   214,   214,   169,   218,   214,   219,   204,
   218,   218,   219,   219,   218,    46,   219,    98,   223,    47,
   -44,   224,     2,   231,   234,   238,     3,   240,    97,    48,
     4,     5,   171,    49,     6,   192,    50,    41,    42,    43,
   194,    44,    45,     7,   193,    51,    52,    21,   195,    53,
   222,   196,   100,     0,    54,    55,    56,    57,    58,    59,
   119,     0,    46,     0,     0,     0,    47,     0,    60,     2,
     0,     0,     0,     3,     0,     0,   212,     4,     5,     0,
    49,     6,     0,    50,    41,    42,    43,     0,    44,    45,
     7,     0,    51,     0,     0,     0,    53,     0,     0,     0,
     0,    54,    55,    56,    57,    58,    59,     0,     0,    46,
     0,     0,     0,    47,     0,    60,     2,     0,     0,     0,
     3,     0,     0,   226,     4,     5,     0,    49,     6,     0,
    50,    41,    42,    43,     0,    44,    45,     7,     0,    51,
     0,     0,     0,    53,     0,     0,     0,     0,    54,    55,
    56,    57,    58,    59,     0,    41,    42,    43,     0,    44,
    45,     0,    60,     2,     0,     0,     0,     3,     0,     0,
     0,     4,     5,     0,     0,     6,     0,    50,     0,     0,
     0,    41,    42,    43,     7,    44,    45,     0,     0,     0,
    53,     0,     0,     0,     0,    54,    55,    56,    57,    58,
    59,    50,     0,     0,     2,    41,    42,    43,     3,    44,
    45,   110,     4,     5,    53,     0,     6,     0,     0,    54,
    55,    56,    57,    58,    59,     7,     0,    50,     0,    41,
    42,    43,    24,    44,    45,     0,     0,     0,     0,     0,
    53,   173,     0,     0,     0,    54,    55,    56,    57,    58,
    59,    50,     0,    41,    42,    43,     0,    44,    45,     0,
     0,     0,     0,     0,   104,     0,     0,     0,     0,    54,
    55,    56,    57,    58,    59,    50,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,   112,     0,
     0,     0,     0,    54,    55,    56,    57,    58,    59,    50,
     1,     0,     2,     0,     0,     0,     3,     0,     0,     0,
     4,     5,    53,     0,     6,     0,     0,    54,    55,    56,
    57,    58,    59,     7,     0,     0,     0,     0,     0,     2,
     0,     0,     0,     3,     0,     0,     0,     4,     5,     0,
     0,     6,     0,     0,     0,     0,     0,     0,     0,     0,
     7
};

static const short yycheck[] = {     0,
    49,    63,    36,    36,    53,    40,    40,    40,    19,    14,
    63,    12,     9,    10,    44,    45,   121,    59,     0,   124,
    50,   224,   203,     4,     5,    90,    37,     7,     8,    61,
    12,     3,   203,   138,    99,   238,    61,    90,    63,    81,
   203,   203,    53,   224,    74,    62,    99,    61,    80,   230,
     0,    65,    59,   234,   235,   104,     6,   238,    11,    12,
   109,   224,   224,   112,   235,   114,    74,   230,   230,    69,
    70,   234,   235,   235,    79,   238,   125,    62,    75,    76,
    15,    16,    62,     3,    64,    35,    66,   144,   145,    39,
    68,   126,    61,    43,    44,    73,    74,    47,   160,    63,
   162,   112,    59,   208,    61,    59,    56,   160,   119,   162,
   159,   141,   142,   143,   144,   145,   146,   147,   148,   149,
   150,   151,   152,   153,   154,   155,   156,   157,   158,   164,
   164,   164,    81,   141,   142,   143,     3,     4,     5,   169,
    59,     3,    61,   205,   148,   149,   150,   151,     3,     4,
     5,    60,     7,     8,    61,    61,    63,    63,    61,    61,
    63,   169,    60,    17,    18,    19,    20,    21,    22,    23,
    24,    25,    26,    28,   223,    59,    61,    32,    63,    59,
    35,   211,   231,    61,    39,    63,    62,    42,    43,    44,
    62,    46,    47,    61,    49,    63,    61,    67,    63,   146,
   147,    56,   203,    58,    59,    78,    60,    62,    77,   203,
    13,   203,    67,    68,    69,    70,    71,    72,   152,   153,
     3,     4,     5,   224,     7,     8,    81,    82,    60,   230,
   224,     3,   224,   234,   235,    63,   230,   238,   230,    63,
   234,   235,   234,   235,   238,    28,   238,    59,    62,    32,
    36,    36,    35,    62,    36,    36,    39,     0,    37,    42,
    43,    44,   119,    46,    47,   154,    49,     3,     4,     5,
   156,     7,     8,    56,   155,    58,    59,    12,   157,    62,
   211,   158,    39,    -1,    67,    68,    69,    70,    71,    72,
    65,    -1,    28,    -1,    -1,    -1,    32,    -1,    81,    35,
    -1,    -1,    -1,    39,    -1,    -1,    42,    43,    44,    -1,
    46,    47,    -1,    49,     3,     4,     5,    -1,     7,     8,
    56,    -1,    58,    -1,    -1,    -1,    62,    -1,    -1,    -1,
    -1,    67,    68,    69,    70,    71,    72,    -1,    -1,    28,
    -1,    -1,    -1,    32,    -1,    81,    35,    -1,    -1,    -1,
    39,    -1,    -1,    42,    43,    44,    -1,    46,    47,    -1,
    49,     3,     4,     5,    -1,     7,     8,    56,    -1,    58,
    -1,    -1,    -1,    62,    -1,    -1,    -1,    -1,    67,    68,
    69,    70,    71,    72,    -1,     3,     4,     5,    -1,     7,
     8,    -1,    81,    35,    -1,    -1,    -1,    39,    -1,    -1,
    -1,    43,    44,    -1,    -1,    47,    -1,    49,    -1,    -1,
    -1,     3,     4,     5,    56,     7,     8,    -1,    -1,    -1,
    62,    -1,    -1,    -1,    -1,    67,    68,    69,    70,    71,
    72,    49,    -1,    -1,    35,     3,     4,     5,    39,     7,
     8,    59,    43,    44,    62,    -1,    47,    -1,    -1,    67,
    68,    69,    70,    71,    72,    56,    -1,    49,    -1,     3,
     4,     5,    63,     7,     8,    -1,    -1,    -1,    -1,    -1,
    62,    63,    -1,    -1,    -1,    67,    68,    69,    70,    71,
    72,    49,    -1,     3,     4,     5,    -1,     7,     8,    -1,
    -1,    -1,    -1,    -1,    62,    -1,    -1,    -1,    -1,    67,
    68,    69,    70,    71,    72,    49,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    62,    -1,
    -1,    -1,    -1,    67,    68,    69,    70,    71,    72,    49,
     6,    -1,    35,    -1,    -1,    -1,    39,    -1,    -1,    -1,
    43,    44,    62,    -1,    47,    -1,    -1,    67,    68,    69,
    70,    71,    72,    56,    -1,    -1,    -1,    -1,    -1,    35,
    -1,    -1,    -1,    39,    -1,    -1,    -1,    43,    44,    -1,
    -1,    47,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    56
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 200 "parser.y"
{alc="short";;
    break;}
case 2:
#line 201 "parser.y"
{alc="int";;
    break;}
case 3:
#line 202 "parser.y"
{alc="long";;
    break;}
case 4:
#line 203 "parser.y"
{alc="float";;
    break;}
case 5:
#line 204 "parser.y"
{alc="double";;
    break;}
case 6:
#line 205 "parser.y"
{alc="void";;
    break;}
case 24:
#line 239 "parser.y"
{ int len = strlen(yylval.sym); 
								char *buffer=(char *)malloc(len);
								int i;
								for (i=0;i<len-1;i++)
								{
									buffer[i] = yylval.sym[i];
								}
								if(checkDeclaration(buffer))
									{
										printf("\nArgument Passed 2: %s\n", yylval.sym);
										printf("correct\n");
										addToTable(0,buffer,"function", alc);
									}
									else
									{
										printf(ANSI_COLOR_RED "ERROR: Function is already declared\n" ANSI_COLOR_RESET);
									}
								;
    break;}
case 25:
#line 258 "parser.y"
{if(checkDeclaration(yylval.sym))
									{
										printf("\nArgument Passed 2: %s\n", yylval.sym);
										printf("correct\n");
										addToTable(0,yylval.sym,"identifier", alc);
									}
									else
									{
										printf(ANSI_COLOR_RED "ERROR: Variable is already declared\n" ANSI_COLOR_RESET);
									}
								;
    break;}
case 127:
#line 469 "parser.y"
{push(stack,globalScope++);;
    break;}
case 128:
#line 471 "parser.y"
{pop(stack); globalScope =  stack->array[stack->top];;
    break;}
case 139:
#line 501 "parser.y"
{pop(stack); globalScope = stack->array[stack->top];;
    break;}
case 140:
#line 504 "parser.y"
{push(stack,globalScope++);;
    break;}
case 141:
#line 507 "parser.y"
{if(checkDeclaration(yylval.sym)==0)
				{
					printf("\nArgument Passed : %s\n", yylval.sym);
				}
			else
			{
				printf(ANSI_COLOR_RED "\nERROR: Variable used is not declared\n" ANSI_COLOR_RESET);
			}
		;
    break;}
case 142:
#line 517 "parser.y"
{if(checkDeclaration(yylval.sym))
				{
					printf("\nArgument Passed 2: %s\n", yylval.sym);
					printf("correct\n");
					addToTable(0,yylval.sym,"identifier", alc);
					printf("\n--------%s--------\n", yylval.sym);
				}
				else
				{
					printf(ANSI_COLOR_RED "ERROR: Variable is already declared\n" ANSI_COLOR_RESET);
				}
			;
    break;}
case 143:
#line 530 "parser.y"
{
				int len = strlen(yylval.sym); 
				char *buffer=(char *)malloc(len);
				int i;
				for (i=0;i<len-1;i++)
				{
					buffer[i] = yylval.sym[i];
				}
	
				if(checkDeclaration(buffer))
				{
					printf("\nArgument Passed 2: %s\n", yylval.sym);
					printf("correct\n");
					addToTable(0,buffer,"identifier", alc);
					printf("\n--------%s--------\n", buffer);
				}
				else
				{
					printf(ANSI_COLOR_RED "ERROR: Variable is already declared\n" ANSI_COLOR_RESET);
				}
			;
    break;}
case 144:
#line 552 "parser.y"
{addToTable(1,yylval.sym,"constant", "");;
    break;}
case 145:
#line 553 "parser.y"
{addToTable(1,yylval.sym,"string", "");;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 554 "parser.y"


#include<stdio.h>
extern int lineNo;
int main()
{
	init();
	yyparse();
	display();
}

int yywrap()
{
	return 1;
}

void yyerror(char *msg)
{
	printf("Error: %s in line %d\n",msg, lineNo);
}